# Generated by Django 5.2.5 on 2025-08-19 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cheating_detection', '0002_initial'),
        ('classes', '0001_initial'),
        ('evaluation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the report', max_length=200)),
                ('report_type', models.CharField(choices=[('student_progress', 'Student Progress Report'), ('class_summary', 'Class Summary Report'), ('evaluation_analysis', 'Evaluation Analysis Report'), ('cheating_report', 'Cheating Detection Report'), ('comprehensive', 'Comprehensive Report')], default='student_progress', max_length=20)),
                ('report_data', models.JSONField(default=dict, help_text='Structured report data')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/pdf/')),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='reports/excel/')),
                ('date_from', models.DateTimeField(blank=True, help_text='Start date for report data', null=True)),
                ('date_to', models.DateTimeField(blank=True, help_text='End date for report data', null=True)),
                ('include_charts', models.BooleanField(default=True, help_text='Include charts and graphs')),
                ('include_detailed_feedback', models.BooleanField(default=True, help_text='Include detailed feedback')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cheating_detections', models.ManyToManyField(blank=True, help_text='Cheating detections included in this report', to='cheating_detection.cheatingdetection')),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='classes.classgroup')),
                ('evaluations', models.ManyToManyField(blank=True, help_text='Evaluations included in this report', to='evaluation.evaluation')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='classes.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'report_report',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('report_type', models.CharField(choices=[('student_progress', 'Student Progress Report'), ('class_summary', 'Class Summary Report'), ('evaluation_analysis', 'Evaluation Analysis Report'), ('cheating_report', 'Cheating Detection Report'), ('comprehensive', 'Comprehensive Report')], max_length=20)),
                ('template_data', models.JSONField(help_text='Template configuration and structure')),
                ('is_default', models.BooleanField(default=False, help_text='Is this a default template')),
                ('is_active', models.BooleanField(default=True, help_text='Is this template active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'db_table': 'report_reporttemplate',
                'unique_together': {('report_type', 'is_default')},
            },
        ),
    ]
