<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-08-19 08:22
=======
# Generated by Django 5.2.5 on 2025-08-18 07:50
>>>>>>> 04a5d8e26f039b06c6cca9c90d5af80fc5c8f558

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheatingDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(help_text='Input data for cheating detection')),
                ('input_image', models.ImageField(blank=True, null=True, upload_to='cheating_detection/')),
                ('input_video', models.FileField(blank=True, null=True, upload_to='cheating_detection/videos/')),
                ('result', models.JSONField(help_text='Detailed detection results')),
                ('cheating_level', models.CharField(choices=[('none', 'No Cheating Detected'), ('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='none', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence score (0-1)')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cheating Detection',
                'verbose_name_plural': 'Cheating Detections',
                'db_table': 'cheating_detection_cheatingdetection',
                'ordering': ['-created_at'],
            },
        ),
    ]
