<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-08-19 08:22
=======
# Generated by Django 5.2.5 on 2025-08-18 07:50
>>>>>>> 04a5d8e26f039b06c6cca9c90d5af80fc5c8f558

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cheating_detection', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheatingdetection',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cheating_detections', to='classes.classgroup'),
        ),
        migrations.AddField(
            model_name='cheatingdetection',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cheating_detections', to='classes.student'),
        ),
    ]
