# Generated by Django 5.2.5 on 2025-08-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the class group', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the class')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the class is currently active')),
                ('subject', models.CharField(blank=True, help_text='Subject of the class', max_length=100)),
            ],
            options={
                'verbose_name': 'Class Group',
                'verbose_name_plural': 'Class Groups',
                'db_table': 'classes_classgroup',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the student', max_length=100)),
                ('email', models.EmailField(help_text="Student's email address", max_length=254)),
                ('student_id', models.CharField(blank=True, help_text='Student ID or roll number', max_length=50)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the student is active in the class')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'classes_student',
                'ordering': ['name'],
            },
        ),
    ]
